# Google travel
- platform: google_travel_time
  name: home_to_daves_work
  api_key: !secret google_api
  origin: zone.home
  destination: zone.work

- platform: google_travel_time
  name: daves_work_to_home
  api_key: !secret google_api
  origin: zone.work
  destination: zone.home

- platform: google_travel_time
  name: home_to_school
  api_key: !secret google_api
  origin: zone.home
  destination: zone.school

#- platform: google_travel_time
#  name: Dave location to home
#  api_key: !secret google_api
#  origin: device_tracker.davidsiphone7
#  destination: zone.home