#Darksky weather
- platform: darksky
  api_key: !secret forecast_key
  monitored_conditions:
    - summary
    - temperature
    - daily_summary
    - hourly_summary
    - temperature_max
    - temperature_min
    - humidity
- platform: moon
- platform: template
  sensors:
    sunrise:
      value_template: '{{ states.sun.sun.attributes.next_rising }}'